### PR TITLE
Css branch

### PR DESCRIPTION
**Pull request by wrose100**
Howdy! I am opening this as a discussion into an alternative site redesign. I think this one has potentially a cleaner, more conservative and modern look to it, which while maybe boring is not a bad thing. Tell me what you think!

### CODE REVIEW

**Comment by wrose100** [comment]
Also this is basically a modification of #21

**Comment by wrose100** [comment]
Comments:
- Is the white too much (maybe a subtle pattern)
- Bootstrap scroll down with Lorena's message
- Boundary of menus

**Comment by tom-robbins** [comment]
u fucking wot m8

**Comment by wrose100** [comment]
closed!

**Pull request merged**
